package org.walker.tprDBHelper.views;

import com.intellij.uiDesigner.core.Spacer;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;
import java.util.ArrayList;

public class CouchDocumentsView extends JFrame {

    private JPanel mainPanel;
    private JPanel keysPanel;
    private JPanel backButtonPanel;
    private JButton backButton;
    private ArrayList<JButton> viewNameButtonList = new ArrayList<>();
    private JPanel panel_Main;
    private JPanel panel_Documents;
    private JPanel panel_Buttons;
    private JButton btn_Back;

    public CouchDocumentsView() {

        $$$setupUI$$$();
        this.setSize(400, 400);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);

        this.add(panel_Main);

    }

    public void displayCouchKeyNames(JSONArray keyNameArray) throws JSONException {
        if (keyNameArray == null) {
            return;
        }

        for (int i = 0; i < keyNameArray.length(); i++) {
            JSONObject a = keyNameArray.getJSONObject(i);
            String keyName = a.getString("key");
            JButton keyNameBTN = new JButton(keyName);
            viewNameButtonList.add(keyNameBTN);
            panel_Documents.add(keyNameBTN);
        }
    }

    public void addBackButtonListener(ActionListener listener) {
        btn_Back.addActionListener(listener);
    }

    public void addSelectedKeyNameListener(ActionListener listenForBeingSelected) {
        for (JButton button : viewNameButtonList) {
            button.addActionListener(listenForBeingSelected);
        }
    }

    public void displayErrorMessage(String errorMessage) {
        JOptionPane.showMessageDialog(this, errorMessage);
    }

    public void setKeysPanel(JPanel keysPanel) {
        this.keysPanel = keysPanel;
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        panel_Main = new JPanel();
        panel_Main.setLayout(new BorderLayout(0, 10));
        panel_Main.add(panel_Documents, BorderLayout.CENTER);
        panel_Buttons = new JPanel();
        panel_Buttons.setLayout(new BorderLayout(0, 0));
        panel_Main.add(panel_Buttons, BorderLayout.SOUTH);
        btn_Back = new JButton();
        btn_Back.setText("Back");
        panel_Buttons.add(btn_Back, BorderLayout.WEST);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel_Main;
    }

    private void createUIComponents() {
        panel_Documents = new JPanel(new GridLayout(0, 1));
    }
}
