package org.walker.tprDBHelper.views;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import org.apache.commons.lang3.StringUtils;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;
import java.awt.event.KeyListener;
import java.util.ArrayList;
import java.util.HashMap;

public class ListTestCasesView extends JFrame {

    private JPanel panel;
    private ArrayList<JButton> testCaseButtonList = new ArrayList<>();
    private JButton btn_SaveToCouch;
    private JPanel btnPanel;
    private JPanel panelMain;
    private JPanel panel_TestCases;
    private JPanel panel_Button;
    private JPanel panel_Main;
    private JPanel panel_Buttons;
    private JButton btn_Back;
    private JScrollPane scroll_TestCases;
    private JTextField txt_Search;
    private JButton btn_Search;
    private JPanel panel_Search;
    private JButton btn_Clear;

    public ListTestCasesView() {

        $$$setupUI$$$();
        this.setSize(600, 600);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);

        txt_Search.requestFocus();

        this.add(panel_Main);
    }

    public void displayAllTestCases(ArrayList<String> keyNameArray, HashMap<String, Boolean> updatedTestCaseMap) {
        if (keyNameArray == null) {
            return;
        }


        for (int i = 0; i < keyNameArray.size(); i++) {
            String keyName = keyNameArray.get(i);
            JButton testCaseBTN = new JButton(StringUtils.abbreviate(keyName, 70));
            testCaseBTN.setActionCommand(keyName);
            if (updatedTestCaseMap.get(keyNameArray.get(i))) {
                testCaseBTN.setBackground(new Color(247, 153, 153));
            }
            testCaseButtonList.add(testCaseBTN);
            panel_TestCases.add(testCaseBTN);
        }

        this.add(panel_Main);
    }

    public void addSelectedKeyNameListener(ActionListener listenForBeingSelected) {
        for (JButton button : testCaseButtonList) {
            button.addActionListener(listenForBeingSelected);
        }
    }

    public void addSaveToCouchButtonListener(ActionListener listenForSaveButtonClick) {
        btn_SaveToCouch.addActionListener(listenForSaveButtonClick);
    }

    public void addSearchButtonListener(ActionListener listener) {
        btn_Search.addActionListener(listener);
        btn_Clear.addActionListener(listener);
    }

    public void addEnterKeyStrokeSearchListener(KeyListener listener) {
        txt_Search.addKeyListener(listener);
    }

    public void setSearchTextFieldFocus() {
        txt_Search.requestFocus();
    }

    public Integer getScrollLocation() {
        return scroll_TestCases.getVerticalScrollBar().getValue();
    }

    public void setScrollBarLocation(int location) {
        scroll_TestCases.getVerticalScrollBar().setValue(location);
    }

    public String getSearchBarText() {
        return txt_Search.getText();
    }

    public void clearSearchBarText() {
        txt_Search.setText("");
    }

    public void clearTestCasePanel() {
        panel_TestCases.removeAll();
        scroll_TestCases.setViewportView(panel_TestCases);
    }


    public void addBackButtonListener(ActionListener listener) {
        btn_Back.addActionListener(listener);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        panel_Main = new JPanel();
        panel_Main.setLayout(new BorderLayout(0, 5));
        panel_Buttons = new JPanel();
        panel_Buttons.setLayout(new FlowLayout(FlowLayout.CENTER, 60, 5));
        panel_Main.add(panel_Buttons, BorderLayout.SOUTH);
        btn_Back = new JButton();
        btn_Back.setPreferredSize(new Dimension(100, 30));
        btn_Back.setText("Back");
        panel_Buttons.add(btn_Back);
        btn_SaveToCouch = new JButton();
        btn_SaveToCouch.setPreferredSize(new Dimension(100, 30));
        btn_SaveToCouch.setText("Save To Couch");
        panel_Buttons.add(btn_SaveToCouch);
        scroll_TestCases = new JScrollPane();
        panel_Main.add(scroll_TestCases, BorderLayout.CENTER);
        scroll_TestCases.setViewportView(panel_TestCases);
        panel_Search = new JPanel();
        panel_Search.setLayout(new GridLayoutManager(1, 3, new Insets(5, 5, 5, 5), -1, -1));
        panel_Main.add(panel_Search, BorderLayout.NORTH);
        txt_Search = new JTextField();
        txt_Search.setMargin(new Insets(2, 6, 2, 6));
        panel_Search.add(txt_Search, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        btn_Search = new JButton();
        btn_Search.setText("Search");
        panel_Search.add(btn_Search, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btn_Clear = new JButton();
        btn_Clear.setText("Clear");
        panel_Search.add(btn_Clear, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel_Main;
    }

    private void createUIComponents() {
        panel_TestCases = new JPanel(new GridLayout(0, 1));
    }
}
