package org.walker.tprDBHelper.views;

import org.walker.tprDBHelper.controllers.DatabaseInfoController;
import org.walker.tprDBHelper.models.CouchDBModel;
import org.walker.tprDataConverter.controllers.FileInputController;
import org.walker.tprDataConverter.models.FileInputModel;
import org.walker.tprDataConverter.views.FileInputView;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;

public class TPRDatabaseHelperView extends JFrame {

    private JPanel panel_Main;
    private JButton btn_DBHelper;
    private JButton btn_Converter;

    public TPRDatabaseHelperView() {

        this.setSize(300, 200);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);

        $$$setupUI$$$();
        btn_DBHelper.addActionListener(this::buttonPressed);
        btn_Converter.addActionListener(this::buttonPressed);


        this.add(panel_Main);

        this.setVisible(true);
    }

    private void buttonPressed(ActionEvent event) {
        String actionEvent = event.getActionCommand();

        if (actionEvent.equalsIgnoreCase("Database Helper")) {
            DatabaseInfoForm dbForm = new DatabaseInfoForm();
            CouchDBModel dbModel = new CouchDBModel();

            new DatabaseInfoController(dbForm, dbModel);

            this.setVisible(false);
        }

        if (actionEvent.equalsIgnoreCase("Data Converter")) {
            new FileInputController(new FileInputModel(), new FileInputView());
        }
    }

    private void createUIComponents() {
        panel_Main = new JPanel(new GridLayout(1, 2));
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel_Main = new JPanel();
        panel_Main.setLayout(new GridBagLayout());
        btn_DBHelper = new JButton();
        btn_DBHelper.setText("Database Helper");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 150.0;
        gbc.weighty = 100.0;
        gbc.fill = GridBagConstraints.BOTH;
        panel_Main.add(btn_DBHelper, gbc);
        btn_Converter = new JButton();
        btn_Converter.setText("Data Converter");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 150.0;
        gbc.weighty = 100.0;
        gbc.fill = GridBagConstraints.BOTH;
        panel_Main.add(btn_Converter, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel_Main;
    }

}
